<?php

/**
 * @file
 * Contains sw_register.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function sw_register_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sw_register':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Registers a Service Worker script for Progressive Web App functionality.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function sw_register_page_attachments(array &$page) {
  $config = \Drupal::config('sw_register.settings');
  $script_path = $config->get('service_worker_js_script_path');

  if (empty($script_path)) {
    return;
  }

  $script_path = 'base:/' . ltrim($script_path, '/');
  $script_url = Url::fromUri($script_path, ['absolute' => TRUE]);

  $page['#attached']['drupalSettings']['sw_register']['path'] = $script_url->toString();
  $page['#attached']['library'][] = 'sw_register/register';
}
